// Generated by CoffeeScript 1.8.0
(function() {
  var CodeCommentCommand, TestStorage, TextCommand,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TestStorage = (function() {
    function TestStorage(string, selecteRange, fileName) {
      this.string = string;
      this.selecteRange = selecteRange;
      this.fileName = fileName;
    }

    return TestStorage;

  })();

  TextCommand = (function() {
    function TextCommand(name) {
      this.name = name;
    }

    TextCommand.prototype.run = function(textStorage) {
      return null;
    };

    return TextCommand;

  })();

  CodeCommentCommand = (function(_super) {
    __extends(CodeCommentCommand, _super);

    function CodeCommentCommand() {
      return CodeCommentCommand.__super__.constructor.apply(this, arguments);
    }

    CodeCommentCommand.prototype.run = function(textStorage) {
      return null;
    };

    return CodeCommentCommand;

  })(Animal);

}).call(this);
