// Generated by CoffeeScript 1.8.0
(function() {
  var TestStorage, TextCommand;

  TestStorage = (function() {
    function TestStorage() {}

    return TestStorage;

  })();

  TextCommand = (function() {
    function TextCommand(name) {
      this.name = name;
    }

    TextCommand.prototype.run = function(textStorage) {
      return null;
    };

    return TextCommand;

  })();

}).call(this);
