// Generated by CoffeeScript 1.8.0
(function() {
  var app, express, server, spawn;

  express = require('express');

  spawn = require('child_process').spawn;

  app = express();

  app.get('/', function(req, res) {
    var zipIOS;
    zipIOS = spawn('./helper/zip.sh');
    return zipIOS.on('exit', function(code, signal) {
      return res.download('./IOS.zip', 'IOS.zip');
    });
  });

  server = app.listen(7461, function() {
    var host, port;
    host = server.address().address;
    port = server.address().port;
    return console.log('Example app listening at http://%s:%s', host, port);
  });

}).call(this);
